spring:
  # 콘솔 텍스트 색깔 설정
  output:
    ansi:
      enabled: always

  profiles:
    active: dev

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # 파일 용량 설정
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

---

spring:
  profiles: dev

---

spring:
  profiles: local
