spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/poje?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

cloud:
  aws:
    s3:
      bucket: pojeawsbucket
    credentials:
      access-key: AKIAUFKQHRXIAR4M5VDK
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

server:
  port: 8081
