spring:
  # 콘솔 텍스트 색깔 설정
  output:
    ansi:
      enabled: always

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # 파일 용량 설정
  servlet:
    multipart:
      location: C:/Users/명수/Documents/공부/스프링/포제
      maxFileSize: 10MB
      maxRequestSize: 20MB

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

default:
  image:
    profile: C:/Users/명수/Documents/공부/스프링/포제/default/profile.PNG
    background: C:/Users/명수/Documents/공부/스프링/포제/default/background.JPG

---

spring:
  profiles:
    active: dev

---

spring:
  profiles:
    active: local
